# See https://developers.cloudflare.com/workers/wrangler/configuration/ for more configuration options
#:schema node_modules/wrangler/config-schema.json
name = "optimizely-edge-delivery-dc"
main = "src/index.ts"
compatibility_date = "2024-10-08"
compatibility_flags = ["nodejs_compat"]

# ED: For CF logging
[observability]
enabled = true

[env.dev.vars]
SNIPPET_ID = "28411280946"
environment = 'prod'
dev_host = 'https://demonchronicles.com/'
