# See https://developers.cloudflare.com/workers/wrangler/configuration/ for more configuration options
#:schema node_modules/wrangler/config-schema.json
name = "edge-delivery-starter"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[env.dev.vars]
SNIPPET_ID = "29061560280"
environment = 'dev'
dev_host = 'example.com'

[env.prod.vars]
environment = 'prod'
